language: scala
sudo: false
scala:
  - 2.12.7
jdk:
  - openjdk11
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.coursier
script: 
  - travis_retry "./travis.sh"
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
